### ISSUE TITLE
Easy way to translate Graphite dashboards to InfluxDB?

### ISSUE THREAD

**Issue by bryanspears** [sitespeedio/grafana-bootstrap-docker#18]
We recently adopted InfluxDB, and I was sad to see there was only the PageSummary dashboard under the examples: https://github.com/sitespeedio/grafana-bootstrap-docker/tree/master/dashboards

Is there an easy way to translate? A fork or other examples out there?

Thanks!

**Comment by soulgalore** [comment]
Hi @bryanspears no there's no easy way, you need to create them yourself. I think like this: the dashboards we have by default in Graphite is there to show what you can do, but when you setup something yourself, you probably need to create your own dashboards. For example, I personally use [the timing dashboard](https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?orgId=1) but if I do new tests (for example I did some tests any work for testing out logged in/vs normal users, I created specific dashboards for that. I think that is the greatest win by using Open Source tools like Grafana, you can do whatever dashboard you need. 

However we are lacking documentation for how data is tagged in InfluxDB, let me know if you have an idea on how we can improve that (I'm not an InfluxDB user myself, so I'm not of best practices etc).

Best
Peter

**Comment by bryanspears** [comment]
I'm new as well to InfluxDB and Sitespeed.io as well.

I was using the example dashboard this weekend and noticed a few things and compared to Influx documentation such as: https://docs.influxdata.com/influxdb/v1.7/concepts/schema_and_data_layout/

A good example of things that didn't translate well from Graphite to InfluxDB would be the backend vs. frontend chart. This can't be done in the same fashion as graphite because you can't "join" or aggregate measurements only fields within a measurement. It appears their new scripting language will be able to join measurements, but Grafana only has beta support for Flux.

https://grafana.com/plugins/grafana-influxdb-flux-datasource
https://github.com/influxdata/flux

I think the only way to fix this would be to change how values are stored. Doing fields instead of all stats stored as individual measurements. Unsure how this pans out for indexing and disk space for Influx, but you could have all timings in one measurement with fields for backend/frontend/etc. Or do what contentSize does and group by a tag. All timings are a measurement `timing` and then add a `timingType` tag of `backend`, `frontend`, etc.

Anyhow. Not expecting this to magically happen for me. Leaving notes, ideas, and findings for others as I contemplate options.

**Comment by soulgalore** [comment]
Thanks for sharing @bryanspears ! Hmm, yeah I your point. For change something like that we need to check with someone that's more an expert on InfluxDb :) 

Best
Peter

**Comment by bryanspears** [comment]
Closing this issue as there's nothing actionable at this time.

I appreciate your time and efforts on this project, @soulgalore !
