### ISSUE TITLE
"bulk" data messes dashboard

### ISSUE THREAD

**Issue by kissifrot** [sitespeedio/grafana-bootstrap-docker#38]
Hello,

New version of sitespeed.io (16.10) seems to break current dashboard: it adds a new "bulk" data level graphite, which renders current queries unusable.
Is there a way to fix it?
![Capture d’écran 2021-03-16 104504](https://user-images.githubusercontent.com/105998/111288780-cb33cd80-8644-11eb-8f6f-d42601d3d038.png)

**Comment by soulgalore** [comment]
Hi @kissifrot can you show me how you run, what parameters do you use? 

Thanks
Peter

**Comment by kissifrot** [comment]
Hello @soulgalore , I used the examples at https://github.com/sitespeedio/dashboard.sitespeed.io , and used `desktop` and `desktopMulti` tests (I only customized graphite/s3 configuration to adapt hosts, credentials and such)

**Comment by soulgalore** [comment]
I see, that one is running on the coming changes in 17.0.0. If you can upgrade the dashboards in the 17.0.0 branch https://github.com/sitespeedio/grafana-bootstrap-docker/tree/17.0.0/datasources/graphite

Sorry I haven't had time to add the docs yet for the change.

**Comment by kissifrot** [comment]
To be precise I run the following config:
```json
{
  "extends": "/config/secrets.json",
  "browsertime": {
    "connectivity": {
      "engine": "throttle",
      "profile": "cable"
    },
    "visualElements": true,
    "iterations": 3,
    "browser": "chrome",
    "video": true,
    "visualMetric": true,
    "chrome": {
      "collectConsoleLog": true,
      "enableTraceScreenshots": true
    },
    "firefox": {
      "includeResponseBodies": "all",
      "disableBrowsertimeExtension": true,
      "windowRecorder": true,
      "geckoProfiler": true
    }
  },
  "cpu": true,
  "gzipHAR": true,
  "html": {
    "fetchHARFiles": true,
    "showScript": true,
    "compareURL": "https://compare.sitespeed.io/"
  },
  "screenshot": {
    "type": "jpg"
  },
  "slug": "bulk",
  "graphite": {
    "namespace": "sitespeed_io.desktopFirstView",
    "addSlugToKey": true
  }
}

```
And the `bulk` slug doesn't seem to be included in any of the queries of https://github.com/sitespeedio/grafana-bootstrap-docker/blob/17.0.0/dashboards/graphite/PageMetricsDesktop.json for example

**Comment by dfrab** [comment]
You fixed, so I can close it :)

**Comment by kissifrot** [comment]
It was fixed in the other repo, thanks :)
