### ISSUE TITLE
please create tags

### ISSUE THREAD

**Issue by efossas** [sitespeedio/grafana-bootstrap-docker#40]
Hi, I believe this repo is the home of the grafana dashboards, which I pull directly from this repo when provisioning the dashboards (I use my own process to get sitespeedio running, as I run it on k8s). I have been using the main branch, but I noticed today that it was updated with changes for 17.0.0. 

Can you please start creating tags or use release branches so that I can pin the versions of the dashboards down?

At the moment, I've switched to using commit references, but it's hard to tell what version of sitespeedio the dashboards are for from that.

**Comment by soulgalore** [comment]
Oops, sorry I though everyone used the tagged Docker container. 

I've created tags for the last updates.

**Comment by efossas** [comment]
🙏 thank you!
