### ISSUE TITLE
ResultURL variable in new dashboards

### ISSUE THREAD

**Issue by zer0kool** [sitespeedio/grafana-bootstrap-docker#41]
The variables are pointing to: https://s3.amazonaws.com/results.sitespeed.io
This is an issue for anyone who is running their instances locally or even storing elsewhere.
https://github.com/sitespeedio/grafana-bootstrap-docker/blob/e63cd587af4844972bcecf3dcbed5b4840f7755c/dashboards/graphite/PageMetricsMobile.json#L22

In addition to this bug. The dashboard will display as shown in the image. 
<img width="445" alt="Screenshot_106" src="https://user-images.githubusercontent.com/15951765/115919007-1bb0fe80-a42d-11eb-914a-15dec5b58603.png">

**Comment by soulgalore** [comment]
I think exporting dashboards in Grafana is broken again, sorry. That should be a variable, so when you import it you should give it a value, I guess didn't happen? The same with *base* and *screenshottype*?

<img width="1168" alt="Screenshot 2021-04-23 at 23 28 22" src="https://user-images.githubusercontent.com/540757/115931579-a45e8780-a48b-11eb-8308-4afc2ebcbb00.png">

**Comment by zer0kool** [comment]
I was able to view and change values, the one thing I don't fully understand is how to get it working on a local environments.
Should one replace the value to the local IP (example: 192.168.1.2) via Grafana variable settings, or  set the result base URL flag at the time of the run?  --resultBaseURL=http://192.168.1.2/ 

Command example: 
`docker-compose run sitespeed.io https://www.example.com/ --graphite.host=graphite --mobile --graphite.addSlugToKey true --slug Homepage --resultBaseURL=http://192.168.1.2/`

Respectfully following the URL scheme, the only value needed to be set is the $resulturl for the images to work?
<img width="492" alt="Screenshot_110" src="https://user-images.githubusercontent.com/15951765/116140190-d2aab580-a68b-11eb-80fd-17dc37c03a21.png">

replacing the value on grafana variable settings will replace the $resulturl to the local environment, but that still doesn't work as Grafana returns a 404 page. 
`<a href=\"$resulturl/$testname/$group.$page.$browser.$connectivity.$screenshottype\">\n<img src=\"$resulturl/$testname/$group.$page.$browser.$connectivity.$screenshottype\"></a>`

building the following url.
http://192.168.1.2:3000/Homepage/www_example_com._.chrome.native.jpg

I fill like I'm still missing to set something on the time of the run? 

Thank you in advanced!

**Comment by zer0kool** [comment]
I got it working. It seems that the following declarations need to be set by default?. That is after the resultBaseURL of course. 
<img width="509" alt="Screenshot_115" src="https://user-images.githubusercontent.com/15951765/116728282-8c5e9a80-a99a-11eb-9d7e-b21dc76ac24b.png">

The issues can now be closed.

**Comment by soulgalore** [comment]
Sorry I missed commenting on the issue. Here's the documentation of what's needed: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#how-to-get-the-latest-videoscreenshot-visible-in-grafana

**Comment by zer0kool** [comment]
Thank you!
