### ISSUE TITLE
Third party CPU usage data not visible in Dashboard

### ISSUE THREAD

**Issue by kissifrot** [sitespeedio/grafana-bootstrap-docker#43]
Hello,

I enabled `--thirdParty.cpu` when running sitespeed.io, but on the dashboard, in the `CPU time spent per tool/domain - enable using --thirdParty.cpu  [Chrome only]` section, I only have empty data, even if I have (sporadic) data in graphite.

Target `aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.thirdparty.tool.*.cpu, 10)` looks okay though :thinking: 

![Capture d’écran du 2021-10-21 09-25-28](https://user-images.githubusercontent.com/105998/138231171-138e2df8-4bd4-47ea-bd09-c6948494c208.png)

**Comment by soulgalore** [comment]
Hi @kissifrot yep that query looks correct, hmm let me check if I have it turned on in any tests so I can see if it works for me.

**Comment by kissifrot** [comment]
Thanks for the fix! (and sorry for the late reply)
