### ISSUE TITLE
template vars import doesn't work for constant `base`

### ISSUE THREAD

**Issue by flecno** [sitespeedio/grafana-bootstrap-docker#8]
After import dashboards the `__input` constant `base` is set to `base` instead of `sitespeed_io` (defined as default? in [pageSummary.__inputs](https://github.com/sitespeedio/grafana-bootstrap-docker/blob/master/dashboards/pageSummary.json#L15))

Is there any API change in grafana 4? Any ideas?

**Comment by soulgalore** [comment]
No need to check that, thanks for reporting.

**Comment by soulgalore** [comment]
This must be a bug in Grafana, the fastest way to solve it I think is to change the dashboards have a hardcoded base. Lets do that for now.

**Comment by soulgalore** [comment]
Or is it on our side, lets debug. Ping @tobli

**Comment by tobli** [comment]
I tried to wrap my head around this, but failed to understand the cause. It certainly looks as if sitespeed.io is doing the right thing.

**Comment by soulgalore** [comment]
Let me try to just test to rename "base" to something else and also try to just insert the dashboard through Grafana import (I should have tried that) to know where the problem is. I tried to see if I could find the bug in the issues for Grafana but no luck.

**Comment by soulgalore** [comment]
Did a quick test just importing one of the dashboards using import in Grafana and then it picks up the right "base" constant. Still it could be something wrong using the API and constants.

**Comment by soulgalore** [comment]
So this is manually fixed by changing the label to "sitespeed_io" as found by @beenanner

**Comment by flecno** [comment]
import works with `grafana/grafana:4.5.2` and `sitespeedio/grafana-bootstrap:6.0` 👍
